name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby & Rust
      uses: oxidize-rb/actions/setup-ruby-and-rust@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cargo-cache: true
        rubygems: '3.5.3'
    - name: Compile the native extension
      run: bundle exec rake compile
    - name: Install the gem
      run: bundle exec rake install
    - name: Run specs
      run: bundle exec rake test
    - name: Run linter
      run: bundle exec rubocop
